#!/bin/bash

if [[ $1 == 'amend' ]]; then
	exit 0
fi

if [[ -t 0 ]]; then
	exit 0
fi

rebasing_file="$PWD"/.git/rebase_in_progress

if [[ -f $rebasing_file ]]; then
	sha_pre_rebase=$(cat $rebasing_file)

	if [[ $(git diff $sha_pre_rebase) ]]; then
		echo "Your rebase resulted in code changes"
		git diff $sha_pre_rebase

    while true; do
  		read -p "Do you want to keep the changes? [Y/n] " -n 1 -r </dev/tty
	  	echo ""

		  if [[ $REPLY =~ ^[Yy]$ ]]; then
			  echo "Cool! All changes kept"
        break
      elif [[ $REPLY =~ ^[Nn]$ ]]; then
  			echo "Discarding changes..."

   			echo ""
	  		git reset --hard $sha_pre_rebase
        break
      else
        echo "Wrong answer: ${REPLY}"
      fi
    done
	else
		echo "Your rebase caused no code changes, good for you"
	fi

	rm $rebasing_file
fi
